defmodule Quix.Repo.Migrations.AddAttemptsAndGuesses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quiz_attempts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true

      add :quiz_id,
          references(:quizzes,
            column: :id,
            name: "quiz_attempts_quiz_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:quiz_attempts, "quiz_attempts_quiz_id_fkey")

    drop table(:quiz_attempts)
  end
end