defmodule Quix.Repo.Migrations.CreateQuestions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:questions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :text, :text, null: false
      add :order, :bigint, null: false

      add :quiz_id,
          references(:quizzes,
            column: :id,
            name: "questions_quiz_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:questions, "questions_quiz_id_fkey")

    drop table(:questions)
  end
end
